### ISSUE TITLE
[FEAT]: option to disable commit status write

### ISSUE THREAD

**Issue by emil-wire** [MediaMarktSaturn/technolinator#306]
### Request Description

I'd like a way to make commit status writes optional. 
Main reason behind the request is that I'm trying technolinator on a broader basis and would like for it to be in the background at first and then operationalize it step by step

Currently, I haven't given the app permission to make commit writes and it fails to complete the scans (which is understandable)

**Comment by beiertu-mms** [comment]
@heubeck I can add a new configuration property (default to enabled/true) and use it [here](https://github.com/MediaMarktSaturn/technolinator/blob/v1.49.4/src/main/java/com/mediamarktsaturn/technolinator/handler/PullRequestHandler.java#L47). WDYT?

**Comment by heubeck** [comment]
That makes absolutely sense, @emil-wire.

We've already a setting, if a _pending_ commit status should be announced, or just the final result, see 
https://github.com/MediaMarktSaturn/technolinator/blob/v1.49.4/src/main/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcher.java#L75-L81 and
https://github.com/MediaMarktSaturn/technolinator/blob/main/src/main/resources/application.properties#L32
, @beiertu-mms .

Would do it in a similar way, the new property would need to disable commit status in general.

There's a setting `APP_ENABLED_REPOS`, in the meanwhile @emil-wire - with that you can enable the app for your entire organization, but have it react only on a limited list of repositories.

**Comment by beiertu-mms** [comment]
@heubeck @emil-wire just to be sure, the new configuration would enabled/disabled commit status update for all repos, right?

**Comment by heubeck** [comment]
> @heubeck @emil-wire just to be sure, the new configuration would enabled/disabled commit status update for all repos, right?

yes, would say so.

**Comment by beiertu-mms** [comment]
@emil-wire this feature will be available with `v1.50.0` by setting the `APP_COMMIT_STATUS_WRITE_ENABLED` variable to `false`.

**Comment by emil-wire** [comment]
@beiertu-mms I've tested 1.50.0 and the feature works well, thank you very much, I appreciate your work!
