### ISSUE TITLE
[Bug]: Swift not installed

### ISSUE THREAD

**Issue by emil-wire** [MediaMarktSaturn/technolinator#359]
### Expected Behavior

Cdxgen supports the swift ecosystem, technolinator should too

### Actual Behavior

Swift doesn't exist in technolinator:

"[feda0072]: Please install swift from https://www.swift.org/download/ or use the cdxgen container image"

**Comment by heubeck** [comment]
Hi @emil-wire, thx for hinting.

In general, I support your request, but Swift seems to be not widely used as of now, is it?

Do you create your own container image derived from the provided one?
If so, you can also _just_ add Swift to only our container - I'm proposing this to avoid adding ~0.5GB to the base image.

If you insist in having Swift included (because you're happy with the pure base image), I'll add it. There's even a package provided for the UBI distribution, what's really nice.

**Comment by beiertu-mms** [comment]
@heubeck should/can we provide a separate "swift" image beside the current one as well?

**Comment by beiertu-mms** [comment]
> > @heubeck should/can we provide a separate "swift" image beside the current one as well?
> 
> that's also a nice idea, but there are for sure much more SDKs that we could add. So maybe something like a "minimal commonly needed" image, and a "full blown, everything's in the box" image...

I guess the problem is then to identify the "commonly needed stuffs" :)

**Comment by heubeck** [comment]
> I guess the problem is then to identify the "commonly needed stuffs" :)

that's what's there now ;)

**Comment by emil-wire** [comment]
I understand the concern, 500MB is not a negligible amount... My problem is as follows: I'd like to avoid forking technolinator and building my own image because you guys have an intense update cadence already and I can't keep up 😅 

I like the idea of another tagged image though which includes swift

**Comment by heubeck** [comment]
> I understand the concern, 500MB is not a negligible amount... My problem is as follows: I'd like to avoid forking technolinator and building my own image because you guys have an intense update cadence already and I can't keep up 😅 
> 
> I like the idea of another tagged image though which includes swift

no worries, @emil-wire .
I'm not available tomorrow, but will follow up asap.

internally, we're not using the built image like-for-like, but re-packaging it to add some config, like shown here: https://github.com/MediaMarktSaturn/technolinator/blob/main/docs/Adoption.md - that was my proposal.

but I like the idea of a (really) fat image variant, so expect this to come up soon.

**Comment by heubeck** [comment]
Hey @emil-wire, your Swift image is there: https://github.com/MediaMarktSaturn/technolinator/pkgs/container/technolinator

`ghcr.io/mediamarktsaturn/technolinator:fat-1.57.0`

please give it a try and report back.

**Comment by emil-wire** [comment]
as always, works perfectly! thank you @heubeck <3

**Comment by heubeck** [comment]
> as always, works perfectly! thank you @heubeck <3

great to hear, thx. @emil-wire 
Looking forward to your next idea :P
